apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Chart.Name }}
spec:
  nodeSelector: null
  output:
    pushSecret:
      name: quay-secret
    to:
      kind: DockerImage
      name: >-
        container-registry.platta-net.hel.fi:443/{{ .Values.project }}/{{ .Chart.Name }}:{{ .Values.wp.image.tag }}
  resources:
    limits:
      cpu: {{ .Values.resources.limits.cpu }}
    requests:
      cpu: {{ .Values.resources.requests.cpu }}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: '{{ .Values.wp.s2iImage.name }}:{{ .Values.wp.s2iImage.tag }}'
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.branch }}
  triggers:
    - type: ConfigChange
  runPolicy: Serial
