apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Values.wp.claimName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wp.storageSize }}
  storageClassName: {{ .Values.wp.storageClassName }}
